In [2]:
import numpy as np

In [3]:
x = np.array([[20, 17, 32, 42, 65],
              [13, 65, 96, 53, 21],
              [45, 63, 74, 38, 64],
              [23, 76, 40, 34, 26],
              [14, 66, 78, 49, 23]])

In [5]:
def layer(x, gamma, beta, eps=1e-5):
    N, D = x.shape
    
    sample_mean = x.mean(axis=1)
    sample_var = x.var(axis=1)
    
    std = np.sqrt(sample_var + eps)
    x_centered = x - sample_mean
    x_norm = x_centered / std
    out = gamma * x_norm + beta
    
    cache = (x_norm, x_centered, std, gamma)

    return out, cache

In [6]:
## it's exactly like above function; we just change axis to 1 for changing normalization area from rows to columns
def batch(x, gamma, beta, eps=1e-5):
    N, D = x.shape
    
    sample_mean = x.mean(axis=0) 
    sample_var = x.var(axis=0)
    
    std = np.sqrt(sample_var + eps)
    x_centered = x - sample_mean
    x_norm = x_centered / std
    out = gamma * x_norm + beta
    
    cache = (x_norm, x_centered, std, gamma)

    return out, cache

In [10]:
print(batch(x, 1, 0)[0].T) 

[[-0.25839035 -0.86130117  1.89486258  0.         -0.77517105]
 [-1.9522604   0.36725691  0.27061035  0.89881296  0.41558018]
 [-1.32416941  1.32416941  0.41380294 -0.99312706  0.57932412]
 [-0.17220346  1.40632822 -0.74621497 -1.32022649  0.8323167 ]
 [ 1.24551176 -0.92919132  1.19608669 -0.68206597 -0.83034118]]


In [8]:
print(layer(x, 1, 0)[0])

[[-0.87558997 -1.07958857 -1.87064616  0.11541284  0.77748801]
 [-1.27882219  0.50998969  2.9568278   0.69247702 -1.02301053]
 [ 0.56452511  0.44375726  1.29738363 -0.09442868  0.73656758]
 [-0.70277616  0.87426804 -1.26721191 -0.30427021 -0.81840843]
 [-1.22121759  0.54310591  1.59910075  0.4826355  -0.94116969]]
